CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611233410_CreateFraudsTable') THEN
    CREATE TABLE "Frauds" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ImpostorDetails" character varying(1000) NOT NULL,
        "ContactInfo" character varying(500) NOT NULL,
        "Comments" character varying(2000),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Frauds" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611233410_CreateFraudsTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260611233410_CreateFraudsTable', '8.0.2');
    END IF;
END $EF$;
COMMIT;

